roles:
  developer:
    policy_arns: ["arn:aws:iam::aws:policy/AdministratorAccess"]
users:
  - username: unclassDev1
    email: "stuart+unclassDev1@spacewego.com"
    projects: ["testProjectA", "shared"]
  - username: unclassDev2
    email: "stuart+unclassDev2@spacewego.com"
    projects: ["shared"]
